<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "treehighlight"
 *
 * Auto generated by Extension Builder 2014-05-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Highlight editable pages in backend page tree',
	'description' => 'Highlights pages in the page tree that the user has edit rights for.',
	'category' => 'be',
	'author' => 'Lorenz Ulrich',
	'author_email' => 'lorenz.ulrich@visol.ch',
	'author_company' => 'visol digitale Dienstleistungen GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>