services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Visol\Treehighlight\EventListeners\HighlightPageTreeEditRights:
    tags:
      - name: event.listener
        identifier: 'treehighlight/backend/hilight-editable-pages'
        event: TYPO3\CMS\Backend\EventListeners\HighlightPageTreeEditRights
