services:
  Visol\Treehighlight\Event\Listener\HighlightPageTreeEditRights:
    tags:
      - name: event.listener
        identifier: 'ext-treehighlight/backend/highlight-editable-pages'
        method: '__invoke'
        event: TYPO3\CMS\Backend\Controller\Event\AfterPageTreeItemsPreparedEvent
